# Generated by Django 5.2.9 on 2026-01-07 18:27

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAnomalyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missing_data_timeout_minutes', models.IntegerField(default=30, help_text="Alert if sensor doesn't send data for this many minutes")),
            ],
            options={
                'db_table': 'globalanomalyconfig',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('full_address', models.CharField(blank=True, max_length=255, null=True)),
                ('h3_index', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'location',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pollutant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pollutant',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AnomalyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('warning_threshold', models.FloatField(help_text='Warning threshold in μg/m³')),
                ('critical_threshold', models.FloatField(help_text='Critical threshold in μg/m³')),
                ('sudden_change_enabled', models.BooleanField(default=True)),
                ('sudden_change_percent', models.FloatField(default=50, help_text='Trigger if value changes by this % in sudden_change_minutes')),
                ('sudden_change_minutes', models.IntegerField(default=10, help_text='Time window for sudden change detection')),
                ('pollutant', models.OneToOneField(db_column='pollutantid', on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_rule', to='sensors.pollutant')),
            ],
            options={
                'db_table': 'anomalyrule',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MonitoringStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(max_length=50, unique=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('decommission_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(db_column='locationid', on_delete=django.db.models.deletion.RESTRICT, to='sensors.location')),
            ],
            options={
                'db_table': 'monitoringstation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QualityNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('norm_type', models.CharField(max_length=50)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('pollutant', models.ForeignKey(db_column='pollutantid', on_delete=django.db.models.deletion.CASCADE, to='sensors.pollutant')),
            ],
            options={
                'db_table': 'qualitynorm',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('calibration_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('measurement_range_max', models.FloatField(blank=True, null=True)),
                ('send_interval_seconds', models.IntegerField(blank=True, null=True)),
                ('monitoring_station', models.ForeignKey(db_column='monitoringstationid', on_delete=django.db.models.deletion.CASCADE, to='sensors.monitoringstation')),
                ('pollutant', models.ForeignKey(db_column='pollutantid', on_delete=django.db.models.deletion.RESTRICT, to='sensors.pollutant')),
            ],
            options={
                'db_table': 'sensor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_percent', models.IntegerField(default=100)),
                ('signal_rssi_dbm', models.IntegerField(default=-50)),
                ('uptime_seconds', models.BigIntegerField(default=0)),
                ('last_reset_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device_status', to='sensors.sensor')),
            ],
            options={
                'db_table': 'device_status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AnomalyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('detected_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('dismissed', 'Dismissed')], default='pending', max_length=50)),
                ('severity', models.CharField(default='warning', max_length=20)),
                ('sensor', models.ForeignKey(db_column='sensorid', on_delete=django.db.models.deletion.CASCADE, to='sensors.sensor')),
            ],
            options={
                'db_table': 'anomalylog',
                'managed': True,
            },
        ),
    ]
