# Generated by Django 5.2.9 on 2026-01-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('warning_threshold', models.FloatField(help_text='Warning threshold in μg/m³')),
                ('critical_threshold', models.FloatField(help_text='Critical threshold in μg/m³')),
                ('sudden_change_enabled', models.BooleanField(default=True)),
                ('sudden_change_percent', models.FloatField(default=50, help_text='Trigger if value changes by this % in sudden_change_minutes')),
                ('sudden_change_minutes', models.IntegerField(default=10, help_text='Time window for sudden change detection')),
            ],
            options={
                'db_table': 'anomalyrule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_percent', models.IntegerField(default=100)),
                ('signal_rssi_dbm', models.IntegerField(default=-50)),
                ('uptime_seconds', models.BigIntegerField(default=0)),
                ('last_reset_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'device_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GlobalAnomalyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missing_data_timeout_minutes', models.IntegerField(default=30, help_text="Alert if sensor doesn't send data for this many minutes")),
            ],
            options={
                'db_table': 'globalanomalyconfig',
                'managed': False,
            },
        ),
    ]
