# Generated by Django 5.2.9 on 2026-01-24 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_anomalyrule_devicestatus_globalanomalyconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anomalyrule',
            options={},
        ),
        migrations.AlterModelOptions(
            name='devicestatus',
            options={},
        ),
        migrations.AlterModelOptions(
            name='globalanomalyconfig',
            options={},
        ),
    ]
