# Generated by Django 5.2.9 on 2026-01-24 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_alter_anomalyrule_options_alter_devicestatus_options_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='anomalyrule',
        #     name='pollutant',
        #     field=models.OneToOneField(db_column='pollutantid', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_rule', to='sensors.pollutant'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='devicestatus',
        #     name='sensor',
        #     field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='device_status', to='sensors.sensor'),
        #     preserve_default=False,
        # ),
    ]
