# Generated by Django 5.2.9 on 2026-01-25 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_anomalyrule_pollutant_devicestatus_sensor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anomalylog',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='monitoringstation',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pollutant',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='qualitynorm',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='anomalyrule',
            name='pollutant',
            field=models.OneToOneField(blank=True, db_column='pollutantid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_rule', to='sensors.pollutant'),
        ),
        migrations.AddField(
            model_name='devicestatus',
            name='sensor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_status', to='sensors.sensor'),
        ),
    ]
