# Generated by Django 5.2.9 on 2026-01-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_alter_anomalylog_options_alter_location_options_and_more'),
        ('sensors', '0006_anomalyrule_pollutant_devicestatus_sensor'),
    ]

    operations = [
    ]
