# Generated by Django 5.2.9 on 2026-01-07 18:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('time_horizon', models.JSONField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'forecast',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ForecastArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('h3_cells', models.JSONField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'forecastarea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ForecastPollutant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_value', models.FloatField()),
                ('uncertainty', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'forecastpollutant',
                'managed': False,
            },
        ),
    ]
