# Generated by Django 5.2.9 on 2026-01-07 18:27

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastArea',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('h3_cells', models.JSONField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'forecastarea',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('forecast_date', models.DateField(auto_now_add=True)),
                ('time_horizon', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forecast_area', models.ForeignKey(db_column='forecastareaid', on_delete=django.db.models.deletion.CASCADE, to='forecasts.forecastarea')),
                ('user', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forecast',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ForecastPollutant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('forecast_timestamp', models.DateTimeField()),
                ('predicted_value', models.FloatField()),
                ('uncertainty', models.FloatField(blank=True, null=True)),
                ('forecast', models.ForeignKey(db_column='forecastid', on_delete=django.db.models.deletion.CASCADE, to='forecasts.forecast')),
                ('pollutant', models.ForeignKey(db_column='pollutantid', on_delete=django.db.models.deletion.RESTRICT, to='sensors.pollutant')),
            ],
            options={
                'db_table': 'forecastpollutant',
                'managed': True,
            },
        ),
    ]
