# Generated by Django 5.2.9 on 2026-01-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecast',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='forecastarea',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='forecastpollutant',
            options={'managed': False},
        ),
    ]
