# Generated by Django 5.2.9 on 2026-01-07 18:27

import django.contrib.gis.db.models.fields
import django.utils.timezone
import django.db.models.deletion
from django.db import migrations, models
import sys

TESTING = 'pytest' in sys.modules

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': '"User"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('area_of_operation', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('h3_cells', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'institution',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AdvancedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('employment_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(db_column='userid', on_delete=django.db.models.deletion.CASCADE, related_name='advanced_profile', to='users.user')),
                ('institution', models.ForeignKey(blank=True, db_column='institutionid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.institution')),
            ],
            options={
                'db_table': 'advanceduser',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('h3_index', models.CharField(blank=True, max_length=15, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(db_column='userid', on_delete=django.db.models.deletion.CASCADE, related_name='resident_profile', to='users.user')),
            ],
            options={
                'db_table': 'resident',
                'managed': True,
            },
        ),
    ]
