# Generated by Django 5.2.9 on 2026-01-24 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advanceduser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={},
        ),
        migrations.AlterModelOptions(
            name='resident',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
