# Generated by Django 5.2.9 on 2026-01-24 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_advanceduser_options_alter_institution_options_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE "advanceduser" ALTER COLUMN "institutionid" DROP NOT NULL;',
            reverse_sql='ALTER TABLE "advanceduser" ALTER COLUMN "institutionid" SET NOT NULL;',
        ),
    ]
