# Generated by Django 5.2.9 on 2026-01-24 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_anomalyrule_pollutant_devicestatus_sensor'),
        ('users', '0002_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to='sensors.monitoringstation'),
        ),
    ]
