# Generated by Django 5.2.9 on 2026-01-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_apikey_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='request_count',
            field=models.IntegerField(default=0),
        ),
    ]
