# Generated by Django 5.2.9 on 2026-01-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_apikey_request_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='limit',
            field=models.IntegerField(default=200),
        ),
    ]
