# Generated by Django 5.2.9 on 2026-01-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_groups_user_user_permissions'),
        ('users', '0005_apikey_limit'),
    ]

    operations = [
    ]
