# Generated by Django 5.2.9 on 2026-01-24 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(help_text='Opis problemu z integralnością danych')),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'report_issue',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.DeleteModel(
            name='ReportScope',
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'managed': True, 'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='reportissue',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='reports.report'),
        ),
        migrations.AddField(
            model_name='reportissue',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.advanceduser'),
        ),
    ]
