# Generated by Django 5.2.9 on 2026-01-24 18:54

import django.db.models.deletion
import pollution_backend.reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reportissue_delete_reportscope_alter_report_options_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='file_url',
        ),
        # migrations.AddField(
        #     model_name='report',
        #     name='advanced_user',
        #     field=models.ForeignKey(db_column='advanceduserid', default=1, on_delete=django.db.models.deletion.RESTRICT, to='users.advanceduser'),
        #     preserve_default=False,
        # ),
        migrations.AddField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=pollution_backend.reports.models.report_upload_path),
        ),
        migrations.AddField(
            model_name='report',
            name='parameters',
            field=models.JSONField(blank=True, db_column='parameters', default=dict),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
