# Generated by Django 5.2.9 on 2026-01-24 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_report_file_url_report_advanced_user_and_more'),
        ('users', '0002_apikey'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='report',
        #     name='advanced_user',
        #     field=models.ForeignKey(db_column='advanceduserid', default=1, on_delete=django.db.models.deletion.RESTRICT, to='users.advanceduser'),
        #     preserve_default=False,
        # ),
    ]
