# Generated by Django 5.2.9 on 2026-01-25 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_report_file_url_report_advanced_user_and_more'),
        ('users', '0003_fix_institution_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='file',
        ),
        migrations.AddField(
            model_name='report',
            name='advanced_user',
            field=models.ForeignKey(blank=True, db_column='advanceduserid', null=True, on_delete=django.db.models.deletion.RESTRICT, to='users.advanceduser'),
        ),
        migrations.AddField(
            model_name='report',
            name='results',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateField(),
        ),
    ]
