# Generated by Django 5.2.9 on 2026-01-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_report_file_report_advanced_user_and_more'),
        ('reports', '0005_report_advanced_user'),
    ]

    operations = [
    ]
