# Generated by Django 5.2.9 on 2026-01-25 15:31

import pollution_backend.reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_merge_20260125_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=pollution_backend.reports.models.report_upload_path),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
