# Generated by Django 5.2.9 on 2026-01-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_report_file_alter_report_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='reportissue',
            name='description',
            field=models.TextField(),
        ),
    ]
