# Generated by Django 5.2.9 on 2026-01-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('sensor_id', models.BigIntegerField(db_index=True)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'measurement',
            },
        ),
    ]
