# Generated by Django 5.2.9 on 2026-01-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('log_level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', max_length=20)),
                ('sensor_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('station_id', models.IntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'systemlog',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True)),
                ('sensor_id', models.BigIntegerField(db_index=True)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'measurement',
                'unique_together': {('time', 'sensor_id')},
            },
        ),
    ]
