# Generated by Django 5.2.9 on 2026-01-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('log_level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', max_length=20)),
                ('sensor_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('station_id', models.IntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'systemlog',
                'ordering': ['-timestamp'],
            },
        ),
    ]
