# Generated by Django 5.2.9 on 2026-01-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0004_alter_systemlog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='id',
        ),
        migrations.AlterField(
            model_name='measurement',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
